version: "3.8"

services: 
  mysql: 
    container_name: mysql-phpmyadmin
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: 123456
    volumes: 
      - ./db:/var/lib/mysql

  pgadmphpmyadminin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80